### ISSUE TITLE
Building with USE_PAGMO causes file (cec2013_data.hpp) to be skipped

### ISSUE THREAD

**Issue by transferorbit** [Tudat/tudatBundle#35]
Starting with the default build configuration (in QT) and then, in _Build Settings_ > _CMake_, setting `USE_PAGMO` to `ON` results in the following "_General Messages_”:
    `C++ Indexer: Skipping file "/Users/kevin/tudatBundle/pagmo2/include/pagmo/detail/cec2013_data.hpp" because it is too big.`

It is not yet clear what effect this will have, if any.

**Comment by DominicDirkx** [comment]
This does not have any impact that I know of, I think it's a CMake thing, where it cannot parse this file because it is gigantic (it should really be a data file, but they've opted to make it a code file). 

As far as I know, this warning does not result in any errors. In facr, the CEC2013 test problems are part of the example applications, which I have not heard any problem about from anyone.

So, thanks for spotting this line in the messy CMake output, but nothing to worry about :)
