### ISSUE TITLE
Compilation problem, compile output enclosed

### ISSUE THREAD

**Issue by tckosvic** [Tudat/tudatBundle#40]
Can't compile,
Opensuse 15.0, gcc7, c,c++,fortran compilers
Boost 1.66 system installed from software management
Test file attached
/home/tom/Desktop/tudat_compiler_output.txt
[tudat_compiler_output.txt](https://github.com/Tudat/tudatBundle/files/3699498/tudat_compiler_output.txt)
Let me know what you might see.
Thanks all, Tom Kosvic

**Comment by DominicDirkx** [comment]
Hi Tom,

The error seems to occur when linking to boost. Could you specify which workflow you used to install/compile Tudat? Did you use the terminal install guide, or our guide at tudat.tudelft.nl? In either case, could you post the CMake output?

Best,

Dominic

**Comment by tckosvic** [comment]
Dominic thank you for prompt response.  I have been tied up for a couple of days and regretfully unable to get back to you.  I am new to github so I am learning that also.
Here is the link to the installation procedure that I am following:
https://tudat.tudelft.nl/installation/setupDevLinux.html
The CMake output log file is attached and also the error log file:
/home/tom/Tudat/build-tudatBundle-Desktop-Debug/CMakeFiles/CMakeOutput.log
[CMakeOutput.log](https://github.com/Tudat/tudatBundle/files/3712396/CMakeOutput.log)
/home/tom/Tudat/build-tudatBundle-Desktop-Debug/CMakeFiles/CMakeError.log
[CMakeError.log](https://github.com/Tudat/tudatBundle/files/3712400/CMakeError.log)

Hope you can find out what is wrong.  As you said all the errors I saw were related to boost.  I also have a system installed boost  from suse software management that is version 1.66.  Maybe compilation should point to that version.
Tom Kosvic

**Comment by DominicDirkx** [comment]
Hi Tom,

Apologies for the delay (usually our reply is a lot quicker...) It's been quite a long time since anyone has tried to install Tudat on an OpenSuse machine (to my knowledge), but my best guess is that this issue is related to a conflict between your system boost, and the boost downloded/compiled by our bundle. 

Concerning the CMake output, could you attach the output that is generated to your console (or to 'General Messages' in Qt) when you run CMake? The beginning should look like something like the example given in Step 3 of:

https://tudat.tudelft.nl/installation/configureTudatLibraries.html#compile-and-test-tudat-libraries

I hope that the output given by CMake will give more information on which boost version is being used. If not, we're going to have to dig into the cmake files and add extra status outputs, to find out where the issue is. If it's the system boost, there may be a compiler incompatibility, or another issue, that is causing these errors,

Best,

Dominc
